# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lenyas/parralel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lenyas/parralel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lenyas/parralel/CMakeFiles /home/lenyas/parralel/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lenyas/parralel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Lab2

# Build rule for target.
Lab2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Lab2
.PHONY : Lab2

# fast build rule for target.
Lab2/fast:
	$(MAKE) -f CMakeFiles/Lab2.dir/build.make CMakeFiles/Lab2.dir/build
.PHONY : Lab2/fast

#=============================================================================
# Target rules for targets named CS

# Build rule for target.
CS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CS
.PHONY : CS

# fast build rule for target.
CS/fast:
	$(MAKE) -f CMakeFiles/CS.dir/build.make CMakeFiles/CS.dir/build
.PHONY : CS/fast

#=============================================================================
# Target rules for targets named DynamicAverage

# Build rule for target.
DynamicAverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DynamicAverage
.PHONY : DynamicAverage

# fast build rule for target.
DynamicAverage/fast:
	$(MAKE) -f CMakeFiles/DynamicAverage.dir/build.make CMakeFiles/DynamicAverage.dir/build
.PHONY : DynamicAverage/fast

helper/threads.o: helper/threads.cpp.o

.PHONY : helper/threads.o

# target to build an object file
helper/threads.cpp.o:
	$(MAKE) -f CMakeFiles/Lab2.dir/build.make CMakeFiles/Lab2.dir/helper/threads.cpp.o
	$(MAKE) -f CMakeFiles/CS.dir/build.make CMakeFiles/CS.dir/helper/threads.cpp.o
	$(MAKE) -f CMakeFiles/DynamicAverage.dir/build.make CMakeFiles/DynamicAverage.dir/helper/threads.cpp.o
.PHONY : helper/threads.cpp.o

helper/threads.i: helper/threads.cpp.i

.PHONY : helper/threads.i

# target to preprocess a source file
helper/threads.cpp.i:
	$(MAKE) -f CMakeFiles/Lab2.dir/build.make CMakeFiles/Lab2.dir/helper/threads.cpp.i
	$(MAKE) -f CMakeFiles/CS.dir/build.make CMakeFiles/CS.dir/helper/threads.cpp.i
	$(MAKE) -f CMakeFiles/DynamicAverage.dir/build.make CMakeFiles/DynamicAverage.dir/helper/threads.cpp.i
.PHONY : helper/threads.cpp.i

helper/threads.s: helper/threads.cpp.s

.PHONY : helper/threads.s

# target to generate assembly for a file
helper/threads.cpp.s:
	$(MAKE) -f CMakeFiles/Lab2.dir/build.make CMakeFiles/Lab2.dir/helper/threads.cpp.s
	$(MAKE) -f CMakeFiles/CS.dir/build.make CMakeFiles/CS.dir/helper/threads.cpp.s
	$(MAKE) -f CMakeFiles/DynamicAverage.dir/build.make CMakeFiles/DynamicAverage.dir/helper/threads.cpp.s
.PHONY : helper/threads.cpp.s

lab1/cs.o: lab1/cs.cpp.o

.PHONY : lab1/cs.o

# target to build an object file
lab1/cs.cpp.o:
	$(MAKE) -f CMakeFiles/CS.dir/build.make CMakeFiles/CS.dir/lab1/cs.cpp.o
.PHONY : lab1/cs.cpp.o

lab1/cs.i: lab1/cs.cpp.i

.PHONY : lab1/cs.i

# target to preprocess a source file
lab1/cs.cpp.i:
	$(MAKE) -f CMakeFiles/CS.dir/build.make CMakeFiles/CS.dir/lab1/cs.cpp.i
.PHONY : lab1/cs.cpp.i

lab1/cs.s: lab1/cs.cpp.s

.PHONY : lab1/cs.s

# target to generate assembly for a file
lab1/cs.cpp.s:
	$(MAKE) -f CMakeFiles/CS.dir/build.make CMakeFiles/CS.dir/lab1/cs.cpp.s
.PHONY : lab1/cs.cpp.s

lab1/dynamic_average.o: lab1/dynamic_average.cpp.o

.PHONY : lab1/dynamic_average.o

# target to build an object file
lab1/dynamic_average.cpp.o:
	$(MAKE) -f CMakeFiles/DynamicAverage.dir/build.make CMakeFiles/DynamicAverage.dir/lab1/dynamic_average.cpp.o
.PHONY : lab1/dynamic_average.cpp.o

lab1/dynamic_average.i: lab1/dynamic_average.cpp.i

.PHONY : lab1/dynamic_average.i

# target to preprocess a source file
lab1/dynamic_average.cpp.i:
	$(MAKE) -f CMakeFiles/DynamicAverage.dir/build.make CMakeFiles/DynamicAverage.dir/lab1/dynamic_average.cpp.i
.PHONY : lab1/dynamic_average.cpp.i

lab1/dynamic_average.s: lab1/dynamic_average.cpp.s

.PHONY : lab1/dynamic_average.s

# target to generate assembly for a file
lab1/dynamic_average.cpp.s:
	$(MAKE) -f CMakeFiles/DynamicAverage.dir/build.make CMakeFiles/DynamicAverage.dir/lab1/dynamic_average.cpp.s
.PHONY : lab1/dynamic_average.cpp.s

lab2/barrier.o: lab2/barrier.cpp.o

.PHONY : lab2/barrier.o

# target to build an object file
lab2/barrier.cpp.o:
	$(MAKE) -f CMakeFiles/Lab2.dir/build.make CMakeFiles/Lab2.dir/lab2/barrier.cpp.o
.PHONY : lab2/barrier.cpp.o

lab2/barrier.i: lab2/barrier.cpp.i

.PHONY : lab2/barrier.i

# target to preprocess a source file
lab2/barrier.cpp.i:
	$(MAKE) -f CMakeFiles/Lab2.dir/build.make CMakeFiles/Lab2.dir/lab2/barrier.cpp.i
.PHONY : lab2/barrier.cpp.i

lab2/barrier.s: lab2/barrier.cpp.s

.PHONY : lab2/barrier.s

# target to generate assembly for a file
lab2/barrier.cpp.s:
	$(MAKE) -f CMakeFiles/Lab2.dir/build.make CMakeFiles/Lab2.dir/lab2/barrier.cpp.s
.PHONY : lab2/barrier.cpp.s

lab2/lut.o: lab2/lut.cpp.o

.PHONY : lab2/lut.o

# target to build an object file
lab2/lut.cpp.o:
	$(MAKE) -f CMakeFiles/Lab2.dir/build.make CMakeFiles/Lab2.dir/lab2/lut.cpp.o
.PHONY : lab2/lut.cpp.o

lab2/lut.i: lab2/lut.cpp.i

.PHONY : lab2/lut.i

# target to preprocess a source file
lab2/lut.cpp.i:
	$(MAKE) -f CMakeFiles/Lab2.dir/build.make CMakeFiles/Lab2.dir/lab2/lut.cpp.i
.PHONY : lab2/lut.cpp.i

lab2/lut.s: lab2/lut.cpp.s

.PHONY : lab2/lut.s

# target to generate assembly for a file
lab2/lut.cpp.s:
	$(MAKE) -f CMakeFiles/Lab2.dir/build.make CMakeFiles/Lab2.dir/lab2/lut.cpp.s
.PHONY : lab2/lut.cpp.s

lab2/main.o: lab2/main.cpp.o

.PHONY : lab2/main.o

# target to build an object file
lab2/main.cpp.o:
	$(MAKE) -f CMakeFiles/Lab2.dir/build.make CMakeFiles/Lab2.dir/lab2/main.cpp.o
.PHONY : lab2/main.cpp.o

lab2/main.i: lab2/main.cpp.i

.PHONY : lab2/main.i

# target to preprocess a source file
lab2/main.cpp.i:
	$(MAKE) -f CMakeFiles/Lab2.dir/build.make CMakeFiles/Lab2.dir/lab2/main.cpp.i
.PHONY : lab2/main.cpp.i

lab2/main.s: lab2/main.cpp.s

.PHONY : lab2/main.s

# target to generate assembly for a file
lab2/main.cpp.s:
	$(MAKE) -f CMakeFiles/Lab2.dir/build.make CMakeFiles/Lab2.dir/lab2/main.cpp.s
.PHONY : lab2/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... Lab2"
	@echo "... rebuild_cache"
	@echo "... CS"
	@echo "... DynamicAverage"
	@echo "... helper/threads.o"
	@echo "... helper/threads.i"
	@echo "... helper/threads.s"
	@echo "... lab1/cs.o"
	@echo "... lab1/cs.i"
	@echo "... lab1/cs.s"
	@echo "... lab1/dynamic_average.o"
	@echo "... lab1/dynamic_average.i"
	@echo "... lab1/dynamic_average.s"
	@echo "... lab2/barrier.o"
	@echo "... lab2/barrier.i"
	@echo "... lab2/barrier.s"
	@echo "... lab2/lut.o"
	@echo "... lab2/lut.i"
	@echo "... lab2/lut.s"
	@echo "... lab2/main.o"
	@echo "... lab2/main.i"
	@echo "... lab2/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

